"""
farm_simulator.py  —  FARM SIDE
=================================
Represents the software that runs on the farm's own computer.

It knows NOTHING about the Magistrala Docker setup — it only uses:
  • farm_credentials.json  (generated by magistrala_setup.py on the server)

All communication with Magistrala is over HTTP, exactly as a real
IoT device on a remote network would behave.
"""

import json
import time
import requests
from datetime import date, timedelta


class FarmSimulator:
    """
    Runs a PCSE crop simulation and publishes each day's state to
    Magistrala via the HTTP adapter.

    Parameters
    ----------
    credentials_path : str
        Path to farm_credentials.json produced by magistrala_setup.py.
    crop_env : CreateCrop
        An already-instantiated CreateCrop environment.
    """

    def __init__(self, credentials_path: str, crop_env):
        with open(credentials_path) as f:
            creds = json.load(f)

        self.farm_id       = creds["farm_id"]
        self.channel_id    = creds["channel_id"]
        self.client_secret = creds["client_secret"]

        # Full publish URL — the only Magistrala endpoint the farm needs.
        # Subtopic pattern:  <farm_id>/daily
        # e.g. http://192.168.1.100/http/channels/<uuid>/messages/farm-001/daily
        adapter = creds["http_adapter_url"].rstrip("/")
        self._publish_url = (
            f"{adapter}/channels/{self.channel_id}/messages/{self.farm_id}/daily"
        )

        self._session = requests.Session()
        self._session.headers.update({
            "Authorization": f"Client {self.client_secret}",
            "Content-Type":  "application/senml+json",
        })

        self.env = crop_env
        print(f"[{self.farm_id}] Pronto. Publicando em: {self._publish_url}")

    # ── internal helpers ─────────────────────────────────────────────────────

    def _sim_date(self, days_gone: int) -> date:
        return self.env.crop_start_date + timedelta(days=days_gone)

    def _build_senml(self, entry: dict) -> list:
        """
        Converts one crop_data entry into a SenML JSON array.

        Each record:
            {"n": "<variable>", "v": <float>, "t": <unix_timestamp>}

        The timestamp is the simulated calendar date, not wall-clock time,
        so historical runs can be ingested without confusion.
        """
        obs       = entry["obs"]
        action    = entry["action"]
        sim_day   = self._sim_date(entry["days_gone"])
        timestamp = int(time.mktime(sim_day.timetuple()))

        records = []

        # All crop model output variables (DVS, LAI, SM, TWSO, TWRT, …)
        for var, values in obs["crop_model"].items():
            v = values[0]
            if v is not None:
                records.append({"n": var, "v": float(v), "t": timestamp})

        # Key weather variables for context
        for var in ("TMIN", "TMAX", "RAIN", "IRRAD", "WIND", "VAP"):
            vals = obs["weather"].get(var)
            if vals and vals[0] is not None:
                records.append({"n": f"weather_{var}", "v": float(vals[0]), "t": timestamp})

        # Management actions applied that day
        records.append({"n": "irrigation_mm", "v": float(action.get("irrigation", 0)), "t": timestamp})
        records.append({"n": "N_applied_kg",  "v": float(action.get("N", 0)),           "t": timestamp})

        return records

    # ── public API ───────────────────────────────────────────────────────────

    def run_day(self, action: dict):
        """
        Runs one simulation day, then immediately sends the result to Magistrala.
        """
        self.env.aply_action(action)
        entry   = self.env.crop_data[-1]
        payload = self._build_senml(entry)
        sim_day = self._sim_date(entry["days_gone"])

        dvs = entry["obs"]["crop_model"].get("DVS", [None])[0]
        sm  = entry["obs"]["crop_model"].get("SM",  [None])[0]

        try:
            r = self._session.post(self._publish_url, json=payload, timeout=10)
            r.raise_for_status()
            print(
                f"[{self.farm_id}] {sim_day}  "
                f"DVS={dvs:.3f}  SM={sm:.3f}  "
                f"irrig={action.get('irrigation', 0):.1f}mm  "
                f"→ HTTP {r.status_code}"
            )
        except requests.RequestException as e:
            print(f"[{self.farm_id}] {sim_day}  FALHA ao enviar: {e}")

    def run_season(self, action_fn=None):
        """
        Runs the full crop season day by day until PCSE signals termination.

        Parameters
        ----------
        action_fn : callable, optional
            action_fn(env) -> dict
            Called every day to decide the action.
            Defaults to no irrigation and no fertilization.
        """
        print(f"[{self.farm_id}] Iniciando temporada de simulação...")
        while True:
            action = action_fn(self.env) if action_fn else {"irrigation": 0, "N": 0}
            self.run_day(action)
            if self.env.crop_data[-1]["done"]:
                break

        total = len(self.env.crop_data)
        print(f"[{self.farm_id}] Temporada concluída — {total} dias simulados e enviados.")
