"""
run_farm.py  —  FARM SIDE  (entry point)
==========================================
This is the script the farm operator runs on their own computer.

Prerequisites:
  1. farm_credentials.json must exist (generated by magistrala_setup.py
     on the Magistrala server and shared with the farm operator).
  2. The Magistrala server must be reachable at the URL in credentials.
  3. PCSE-Gym and its dependencies must be installed locally.

Usage:
    python run_farm.py
    python run_farm.py --credentials /path/to/farm_credentials.json
"""

import argparse
import os
import sys

# Allow running from any working directory
_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(_DIR, "..", "PCSE-Gym"))

from pcse.fileinput import CABOFileReader, YAMLCropDataProvider
from pcse.util import WOFOST80SiteDataProvider

from crop_create import CreateCrop
from farm_simulator import FarmSimulator

# ── crop configuration (edit to change farm location / crop / soil) ──────────
AGRO_CONFIG = os.path.join(
    _DIR, "..", "PCSE-Gym", "pcse_gym", "envs", "configs", "agro", "potato_cropcalendar.yaml"
)
SOIL_FILE = os.path.join(
    _DIR, "..", "PCSE-Gym", "pcse_gym", "envs", "configs", "soil", "ec3.CAB"
)

# Suzano, SP — Brazil
LATITUDE  = -23.54
LONGITUDE = -46.32
# ─────────────────────────────────────────────────────────────────────────────


def build_crop_env() -> CreateCrop:
    return CreateCrop(
        latitude=LATITUDE,
        longitude=LONGITUDE,
        model_config="Wofost80_NWLP_FD.conf",
        agro_config=AGRO_CONFIG,
        crop_parameters=YAMLCropDataProvider(force_reload=True),
        site_parameters=WOFOST80SiteDataProvider(
            WAV=10,       # initial water in soil profile [cm]
            NAVAILI=10,   # initial N pool [kg/ha]
            PAVAILI=50,   # initial P pool [kg/ha]
            KAVAILI=100,  # initial K pool [kg/ha]
        ),
        soil_parameters=CABOFileReader(SOIL_FILE),
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--credentials",
        default=os.path.join(_DIR, "farm_credentials.json"),
        help="Caminho para farm_credentials.json",
    )
    args = parser.parse_args()

    if not os.path.exists(args.credentials):
        print(
            f"[ERRO] Arquivo de credenciais não encontrado: {args.credentials}\n"
            "Execute magistrala_setup.py no servidor Magistrala primeiro.",
            file=sys.stderr,
        )
        sys.exit(1)

    print("Inicializando ambiente de simulação da cultura...")
    crop_env = build_crop_env()

    farm = FarmSimulator(
        credentials_path=args.credentials,
        crop_env=crop_env,
    )

    # Estratégia de ação: sem irrigação e sem fertilizante por padrão.
    # Substitua esta função por um agente de IA quando estiver pronto.
    def no_intervention(env):
        return {"irrigation": 0, "N": 0}

    farm.run_season(action_fn=no_intervention)


if __name__ == "__main__":
    main()
