"""
run_farm.py  —  FARM SIDE  (entry point)
==========================================
This is the script the farm operator runs on their own computer.

Prerequisites:
  1. farm_credentials.json must exist (generated by magistrala_setup.py
     on the Magistrala server and shared with the farm operator).
  2. The Magistrala server must be reachable at the URL in credentials.
  3. PCSE-Gym and its dependencies must be installed locally.

Usage:
    python run_farm.py
    python run_farm.py --credentials /path/to/farm_credentials.json
"""

import argparse
import json
import os
import sys
from urllib.parse import urlparse

# Allow running from any working directory
_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(_DIR, "..", "PCSE-Gym"))

from pcse.fileinput import CABOFileReader, YAMLCropDataProvider
from pcse.util import WOFOST80SiteDataProvider

from command_listener import CommandListener
from crop_create import CreateCrop
from farm_simulator import FarmSimulator

# ── crop configuration (edit to change farm location / crop / soil) ──────────
AGRO_CONFIG = os.path.join(
    _DIR, "..", "PCSE-Gym", "pcse_gym", "envs", "configs", "agro", "potato_cropcalendar.yaml"
)
SOIL_FILE = os.path.join(
    _DIR, "..", "PCSE-Gym", "pcse_gym", "envs", "configs", "soil", "ec3.CAB"
)

# Suzano, SP — Brazil
LATITUDE  = -23.54
LONGITUDE = -46.32
# ─────────────────────────────────────────────────────────────────────────────


def build_crop_env(wav: float = 10) -> CreateCrop:
    return CreateCrop(
        latitude=LATITUDE,
        longitude=LONGITUDE,
        model_config="Wofost80_NWLP_FD.conf",
        agro_config=AGRO_CONFIG,
        crop_parameters=YAMLCropDataProvider(force_reload=True),
        site_parameters=WOFOST80SiteDataProvider(
            WAV=wav,      # initial water in soil profile [cm] (baixo = solo seco)
            NAVAILI=10,   # initial N pool [kg/ha]
            PAVAILI=50,   # initial P pool [kg/ha]
            KAVAILI=100,  # initial K pool [kg/ha]
        ),
        soil_parameters=CABOFileReader(SOIL_FILE),
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--credentials",
        default=os.path.join(_DIR, "farm_credentials.json"),
        help="Caminho para farm_credentials.json",
    )
    parser.add_argument("--mqtt-host", default=None,
                        help="Host do broker MQTT (default: host do magistrala_url das credenciais)")
    parser.add_argument("--mqtt-port", type=int, default=1883)
    parser.add_argument("--decision-timeout", type=float, default=120.0,
                        help="Segundos a aguardar a decisão da IA por dia antes do fallback")
    parser.add_argument("--open-loop", action="store_true",
                        help="Roda sem esperar a IA (no_intervention), como antes")
    parser.add_argument("--max-days", type=int, default=None,
                        help="Limita a temporada a N dias (teste do loop sem estourar a cota do LLM)")
    parser.add_argument("--wav", type=float, default=10,
                        help="Água inicial no perfil do solo [cm]. Baixo (ex.: 1-2) = solo seco p/ forçar irrigação")
    args = parser.parse_args()

    if not os.path.exists(args.credentials):
        print(
            f"[ERRO] Arquivo de credenciais não encontrado: {args.credentials}\n"
            "Execute magistrala_setup.py no servidor Magistrala primeiro.",
            file=sys.stderr,
        )
        sys.exit(1)

    print("Inicializando ambiente de simulação da cultura...")
    crop_env = build_crop_env(wav=args.wav)

    farm = FarmSimulator(
        credentials_path=args.credentials,
        crop_env=crop_env,
    )

    def no_intervention(env):
        return {"irrigation": 0, "N": 0}

    if args.open_loop:
        print("Modo open-loop: sem intervenção da IA.")
        farm.run_season(action_fn=no_intervention, max_days=args.max_days)
        return

    # ── Loop fechado com a IA ────────────────────────────────────────────────
    with open(args.credentials) as f:
        creds = json.load(f)
    mqtt_host = args.mqtt_host or (urlparse(creds["magistrala_url"]).hostname or "localhost")

    listener = CommandListener(
        host=mqtt_host,
        port=args.mqtt_port,
        domain_id=creds["domain_id"],
        channel_id=creds["channel_id"],
        client_id=creds["client_id"],
        client_secret=creds["client_secret"],
        protocol_id=f"{creds['farm_id']}-listener",
    )
    listener.start()
    print(f"Loop fechado ativo (broker {mqtt_host}:{args.mqtt_port}, "
          f"timeout {args.decision_timeout}s/dia).")

    def ai_decision(env):
        # Dia 1 ainda não publicou nada → sem ação prévia.
        epoch = farm.last_published_epoch
        if epoch is None:
            return {"irrigation": 0, "N": 0}
        cmd = listener.wait_for(epoch, timeout=args.decision_timeout)
        if cmd is None:
            print(f"[run_farm] sem comando para t={epoch} em {args.decision_timeout}s "
                  f"— fallback no_intervention")
            return {"irrigation": 0, "N": 0}
        print(f"[run_farm] aplicando decisão da IA (t={epoch}): "
              f"irrig={cmd['irrigation']}mm N={cmd['N']}kg")
        return cmd

    try:
        farm.run_season(action_fn=ai_decision, max_days=args.max_days)
    finally:
        listener.stop()


if __name__ == "__main__":
    main()
