networks:
  kafka-network:

volumes:
  magistrala-db-volume: {}
  zookeeper_data: {}
  kafka_data: {}

services:
  ui-backend-db:
    image: postgres:16.2-alpine
    container_name: magistrala-db
    restart: on-failure
    command: postgres -c max_connections=100 -c wal_level=logical
    environment:
      POSTGRES_USER: magistrala_user
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: magistrala_db
      SMQ_POSTGRES_MAX_CONNECTIONS: 100
    ports:
      - 6008:5432
    networks:
      - kafka-network
    volumes:
      - magistrala-db-volume:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - "2181:2181"
    networks:
      - kafka-network
    volumes:
      - zookeeper_data:/bitnami/confluent

  kafka1:
    image: confluentinc/cp-kafka:7.2.2
    container_name: kafka1
    ports:
      - "9091:9091"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka1
    depends_on:
      - zookeeper
    networks:
      - kafka-network
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:19091 --list"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka1:19091"]
        schemaRegistry:
          enabled: false
        redpanda:
          adminApi:
            enabled: false
        kafkaConnect:
          enabled: true
          clusters:
            - name: kafka-connect
              url: http://kafka-connect:8083
    ports:
      - 8080:8080
    depends_on:
      kafka1:
        condition: service_healthy
      kafka-connect:
        condition: service_started
    networks:
      - kafka-network

  kafka-connect:
    image: debezium/connect:2.6  # <-- Altere esta linha
    container_name: kafka-connect
    ports :
      - "8083:8083"
    environment:
      # As variáveis de ambiente são as mesmas
      BOOTSTRAP_SERVERS: "kafka1:19091" # <-- O Debezium usa essa variável
      GROUP_ID: "debezium-connect-cluster"
      CONFIG_STORAGE_TOPIC: "connect_configs"
      OFFSET_STORAGE_TOPIC: "connect_offsets"
      STATUS_STORAGE_TOPIC: "connect_status"
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1
      KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      KEY_CONVERTER_SCHEMAS_ENABLE: false
      VALUE_CONVERTER_SCHEMAS_ENABLE: false
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      # A variável CONNECT_PLUGIN_PATH não é mais necessária
    depends_on:
      kafka1:
        condition: service_healthy
    networks:
      - kafka-network